### ISSUE TITLE
sopa did u get term

### ISSUE THREAD

**Issue by STEELIX-FAN** [majorsopa/wii-remote-cult#10]
sopa
pls respond
SOPA

**Comment by STEELIX-FAN** [comment]
SOpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaa

**Comment by majorsopa** [comment]
yes i did

**Comment by STEELIX-FAN** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by STEELIX-FAN** [comment]
what is yor new dis cord

**Comment by majorsopa** [comment]
`majorsopa#0001`

**Comment by STEELIX-FAN** [comment]
ok

**Comment by STEELIX-FAN** [comment]
sol bed
